codecov:
  notify:
    require_ci_to_pass: no

codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        threshold: 1%
    patch: no
    changes: no
    
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
   
comment: false
