Skip to content
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @oscarg933 Sign out
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
@oscarg933	oscarg933

Oscar Gomez
oscarg933
Developer Program Member
'bundle exec rake spec' Instant-transmission.git
@Maxprofs
Tucson, AZ https://github.com/oscarg933/Book-Hub.git.patch
Organizations
@squareinc   @Maxprofs
Overview
Repositories 2.5k
Projects 6
Stars 2.6k
Followers 0
Following 3

Find a repository…
  
btstack
Forked from bluekitchen/btstack
Dual-mode Bluetooth stack, with small memory footprint.
 C  220 Updated a minute ago
QuantumComputing
Forked from corbett/QuantumComputing
High(ish) frequency trading bot for cryptocurrencies, using Machine Learning for future price predictions
 Roff  90 GNU General Public License v3.0 Updated 2 minutes ago
oscarg933.github.io
Http://hackersprayer.AI http://pulse.AI http://AI.AI http://webmaster.io http://trojanhorseretract.io
 Io  2 GNU General Public License v3.0 Updated 5 minutes ago
cheatsheets-ai
Forked from kailashahirwar/cheatsheets-ai
Essential Cheat Sheets for deep learning and machine learning researchers
 2,687 MIT License Updated 6 minutes ago
verbose-octo-chainsaw
<Verbose.render>https://github.com/oscarg933/mlcourse.ai.git
 Io  2 GNU Lesser General Public License v3.0 Updated 8 minutes ago
spyder
Forked from spyder-ide/spyder
Official repository for Spyder - The Scientific Python Development Environment
 Python  835 MIT License Updated 9 minutes ago
Anaconda-Navigator-and-Python-updation
Forked from nikhil133/Anaconda-Navigator-and-Python-updation
Update your Anaconda IDE and python
 Io  5 Updated 15 minutes ago
aluminum
Forked from CreativeCodingLab/aluminum
Quantum core real-time Jenkins react plug-in
 C++  6 Updated 16 minutes ago
python-cox-week4
Forked from python-cox-class/python-cox-week4
This is a test repository showing some of the things we can do with Github for week 4
 Io  12 Apache License 2.0 Updated an hour ago
clc-python-sdk
Forked from CenturyLinkCloud/clc-python-sdk
CenturyLink Cloud CLI & Python SDK
 Python  29 Apache License 2.0 Updated an hour ago
xfinity-usage
Forked from jantman/xfinity-usage
Python/selenium script to get Xfinity bandwidth usage
 Python  12 GNU Affero General Public License v3.0 Updated an hour ago
yasea
Forked from begeekmyfriend/yasea
RTMP live streaming client for Android
 C  937 MIT License Updated 2 hours ago
deeplearning.ai_JupyterNotebooks
Forked from marsggbo/deeplearning.ai_JupyterNotebooks
DeepLearning.ai课程学习Jupyter Notebook作业
 Jupyter Notebook  210 Updated 2 hours ago
software-factory
Forked from redhat-cip/software-factory
The ready to use Continuous Integration platform
 16 Updated 2 hours ago
jQuery.pulsate
Forked from Kilian/jQuery.pulsate
jQuery.pulsate.js adds a pulsating effect to elements. Useful for drawing the users attention.
 HTML  19 MIT License Updated 3 hours ago
symmetrical-octo-barnacle
Hackerspray.git extreme learning
 Io  2 Updated 3 hours ago
travis_anaconda_jupyter
Forked from ghego/travis_anaconda_jupyter
Testing Jupyter notebooks with Travis.ci
 Io  4 MIT License Updated 3 hours ago
Satallite-image-ML-for-identifying-Trees-
Forked from arshadshk/Satallite-image-ML-for-identifying-Trees-
High(ish) frequency trading bot for cryptocurrencies, using Machine Learning for future price predictions
 Python  1 Updated 3 hours ago
SmartTP
Forked from lll7/SmartTP
SmartTP uC codes.
 C  1 Updated 4 hours ago
vscode-tslint
Forked from Microsoft/vscode-tslint
A tslint integration for vscode Hackerspray extreme learning
 TypeScript  78 Other Updated 5 hours ago
pipelines-xamarin
Forked from MicrosoftDocs/pipelines-xamarin
Sample Xamarin application for VSTS Pipelines docs Hackerspray extreme learning
 C#  18 Other Updated 5 hours ago
octobarnacle-azure-pipeline-docs
Py.planetHackerspray extreme learning
 1 Apache License 2.0 Updated 5 hours ago
vscode-eslint
Forked from Microsoft/vscode-eslint
VSCode extension to integrate eslint into VSCode Hackerspray extreme learning
 TypeScript  114 Other Updated 5 hours ago
vscode-cpptools
Forked from Microsoft/vscode-cpptools
Official repository for filing issues against and getting support for the Microsoft C/C++ extension for VS Code Hackerspray extreme learning
 TypeScript  527 Other Updated 5 hours ago
face_specific_augm
Forked from iacopomasi/face_specific_augm
Face Renderer to perform Domain (Face) Specific Data Augmentation
 Python  96 Updated 5 hours ago
lbry
Forked from lbryio/lbry
A fully decentralized network for distributing data
 Python  292 MIT License Updated 5 hours ago
travis-build
Forked from travis-ci/travis-build
.travis.yml => build.sh converter
 Ruby  382 MIT License Updated 5 hours ago
oauthlib
Forked from oauthlib/oauthlib
A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
 Python  375 BSD 3-Clause "New" or "Revised" License Updated 5 hours ago
elasticsearch-gmail
Forked from oliver006/elasticsearch-gmail
Index your Gmail Inbox with Elasticsearch
 Python  134 Updated 5 hours ago
Quakespasm-OpenVR
Forked from Zackin5/Quakespasm-OpenVR
Vive support integrated into Dominic Szablewski's Oculus modification of Quakespasm.
 C  3 GNU General Public License v2.0 Updated 5 hours ago
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
