# -*- coding: utf-8 -*-
#
# Copyright © Spyder Project Contributors
# Licensed under the terms of the MIT License
#

"""
Configuration file for Pytest

NOTE: DO NOT add fixtures here. It could generate problems with
      QtAwesome being called before a QApplication is created.
"""

import concurrent.futures
import os
import os.path as osp
import re
import stat
import sys
from unittest.mock import patch

# ---- To activate/deactivate certain things for pytest's only
# NOTE: Please leave this before any other import here!!
os.environ['SPYDER_PYTEST'] = 'True'


# ---- Tests to skip on the first CI run
SKIP_ON_FIRST_CI_RUN = ["test_mainwindow.py::test_update_outline"]

# ---- Main file where we record tests that passed
# This way a CI restart (e.g. after a segfault) can skip them. This is written
# directly by a pytest hook (see pytest_runtest_logreport), which is robust to
# output getting printed inline with a test's result line -- unlike parsing
# the textual log, where e.g. a Qt warning on Windows can split the node id
# from its PASSED marker and prevent the test from ever being recorded
# (so it re-runs, and may re-flake, forever).
PASSED_TESTS_FILE = "passed_tests.txt"


# ---- Pytest adjustments
import pytest


def pytest_addoption(parser):
    """Add extra options for pytest.

    --run-slow: Run slow tests.
    --remote-client: Run remote-client tests.
    """
    parser.addoption("--run-slow", action="store_true",
                     default=False, help="Run slow tests")
    parser.addoption("--remote-client", action="store_true",
                     default=False, help="Run remote-client tests")


def get_passed_tests():
    """
    Get the list of passed tests by inspecting the log generated by pytest.

    This is useful on CIs to restart the test suite from the point where a
    segfault was thrown by it.
    """
    tests = []

    # Primary source: tests recorded directly by the pytest_runtest_logreport
    # hook. Robust to inline output corrupting the textual result line.
    if osp.isfile(PASSED_TESTS_FILE):
        with open(PASSED_TESTS_FILE) as f:
            tests.extend(line.strip() for line in f if line.strip())

    # Fallback source: parse the textual pytest log. Kept for robustness (and
    # to honor the SKIP_ON_FIRST_CI_RUN special-casing below).
    # This assumes the pytest log is placed next to this file. That's where
    # we put it on CIs.
    if osp.isfile('pytest_log.txt'):
        with open('pytest_log.txt') as f:
            logfile = f.readlines()

        # Detect all tests that passed before.
        # Note: capture only the test node id (path::class::test[params]), not
        # a greedy `.*`. Otherwise output printed inline with the result -- e.g.
        # a Qt warning on Windows like "... test_x QWindowsWindow::setGeometry:
        # ... PASSED" -- gets folded into group(1), which then never matches the
        # clean node id, so the test is never recorded as passed and is re-run
        # (and possibly re-flakes) on every CI restart.
        test_re = re.compile(
            r'(spyder\S*\.py(?:::\w+)*(?:\[.*?\])?) .*(SKIPPED|PASSED|XFAIL)'
        )
        for line in logfile:
            match = test_re.match(line)
            if match:
                if any(
                    skipped_first_run in line
                    for skipped_first_run in SKIP_ON_FIRST_CI_RUN
                ):
                    passed_first_run = "passed_tests_skipped_on_first_run.txt"
                    if "PASSED" in line or "XFAIL" in line:
                        with open(passed_first_run, "w+") as f:
                            f.write(match.group(1))
                            tests.append(match.group(1))
                            continue
                    else:
                        if osp.isfile(passed_first_run):
                            with open(passed_first_run) as f:
                                passed_first_run_contents = f.readlines()
                            if match.group(1) in passed_first_run_contents:
                                tests.append(match.group(1))
                            else:
                                continue
                else:
                    tests.append(match.group(1))

    return tests


def pytest_collection_modifyitems(config, items):
    """
    Decide what tests to run (slow or fast) according to the --run-slow
    option.
    """
    passed_tests = get_passed_tests()
    slow_option = config.getoption("--run-slow")
    remote_client_option = config.getoption("--remote-client")

    skip_slow = pytest.mark.skip(reason="Need --run-slow option to run")
    skip_fast = pytest.mark.skip(reason="Don't need --run-slow option to run")
    skip_passed = pytest.mark.skip(reason="Test passed in previous runs")
    skip_first_run = pytest.mark.skip(reason="Test skipped in first CI run")
    skip_remote = pytest.mark.skip(
        reason="Skipping remote test because --remote-client was not set"
    )
    skip_non_remote = pytest.mark.skip(
        reason="Skipping non-remote test because --remote-client was set"
    )

    # Break test suite in CIs according to the following criteria:
    # * Mark all main window tests, and a percentage of the IPython console
    #   ones, as slow.
    # * All other tests will be considered as fast.
    # This provides a more balanced partitioning of our test suite (in terms of
    # necessary time to run it) between the slow and fast slots we have on CIs.
    slow_items = []
    if os.environ.get("CI") and not os.environ.get(
        "SPYDER_TEST_REMOTE_CLIENT"
    ):
        slow_items = [
            item for item in items if 'test_mainwindow' in item.nodeid
        ]

        ipyconsole_items = [
            item for item in items if 'test_ipythonconsole' in item.nodeid
        ]

        if os.name == 'nt':
            percentage = 0.4
        elif sys.platform == 'darwin':
            percentage = 0.3
        else:
            percentage = 0.3

        for i, item in enumerate(ipyconsole_items):
            if i < len(ipyconsole_items) * percentage:
                slow_items.append(item)

    def mark_item(item):
        if int(os.environ.get("CI_RUN_NUMBER", -1)) == 0 and any(
            skipped_first_run in item.nodeid
            for skipped_first_run in SKIP_ON_FIRST_CI_RUN
        ):
            item.add_marker(skip_first_run)
            return

        if remote_client_option and "remote_test" not in item.keywords:
            item.add_marker(skip_non_remote)
        elif not remote_client_option and "remote_test" in item.keywords:
            item.add_marker(skip_remote)

        if slow_option and item not in slow_items:
            item.add_marker(skip_fast)
        elif not slow_option and item in slow_items:
            item.add_marker(skip_slow)

        if item.nodeid in passed_tests:
            item.add_marker(skip_passed)

    concurrent.futures.ThreadPoolExecutor().map(mark_item, items)


def pytest_runtest_logreport(report):
    """Record tests that pass (or xfail) so a CI restart can skip them.

    Writing the node id directly here -- rather than parsing it back out of
    the textual pytest log in get_passed_tests() -- is robust to output
    printed inline with a test's result line (e.g. a Qt "setGeometry" warning
    on Windows that splits the node id from its PASSED marker), which would
    otherwise prevent the test from ever being recorded and make it re-run
    (and possibly re-flake) on every restart.

    Only active on CIs, where the restart mechanism is used. Locally it would
    otherwise silently skip tests on the next run. A test skipped on the first
    CI run (see SKIP_ON_FIRST_CI_RUN) is not recorded here: skips are ignored,
    so it still runs on later attempts until it actually passes.
    """
    if not os.environ.get("CI"):
        return

    passed = report.when == "call" and report.passed
    xfailed = report.skipped and hasattr(report, "wasxfail")
    if passed or xfailed:
        # Prevent `PermissionError` between tests runs if
        # file already exists
        if osp.isfile(PASSED_TESTS_FILE):
            os.chmod(PASSED_TESTS_FILE, stat.S_IRUSR | stat.S_IWUSR)

        with open(PASSED_TESTS_FILE, "a") as f:
            f.write(report.nodeid + "\n")


@pytest.fixture(scope="session", autouse=True)
def mute_error_message_box(request):
    """
    Prevent modal error dialogs from freezing headless remote-client tests.

    When a remote session drops, the remote explorer's error handler shows a
    modal ``QMessageBox.critical()``. With no user to dismiss it, that call
    blocks the Qt event loop forever, hanging the whole test run until the CI
    job times out (30 min). Turn it into a no-op for the remote-client test
    session (it can fire from async callbacks at any point, including during
    fixture setup/teardown, so this is session-scoped).

    Only ``critical`` (the error dialog) is muted; ``warning``/``question`` are
    used and asserted on by some tests, so they are left untouched.
    """
    if not request.config.getoption("--remote-client"):
        yield
        return

    from qtpy.QtWidgets import QMessageBox

    with patch.object(
        QMessageBox, "critical",
        return_value=QMessageBox.StandardButton.Ok,
    ):
        yield


@pytest.fixture(autouse=True)
def reset_conf_before_test(request):
    # To prevent running this fixture for a specific test, you need to use this
    # marker.
    if 'no_reset_conf' in request.keywords:
        return

    from spyder.config.manager import CONF
    CONF.reset_to_defaults(notification=False)

    from spyder.plugins.completion.api import COMPLETION_ENTRYPOINT
    from spyder.plugins.completion.plugin import CompletionPlugin

    from importlib.metadata import entry_points

    # Restore completion clients default settings, since they
    # don't have default values on the configuration.
    provider_configurations = {}
    for entry_point in entry_points(group=COMPLETION_ENTRYPOINT):
        Provider = entry_point.load()
        provider_name = Provider.COMPLETION_PROVIDER_NAME

        (provider_conf_version,
         current_conf_values,
         provider_defaults) = CompletionPlugin._merge_default_configurations(
            Provider, provider_name, provider_configurations)

        new_provider_config = {
            'version': provider_conf_version,
            'values': current_conf_values,
            'defaults': provider_defaults
        }
        provider_configurations[provider_name] = new_provider_config

    CONF.set('completions', 'provider_configuration', provider_configurations,
             notification=False)
