name: Windows tests

on:
  push:
    branches:
    - master
    - 2.*
  pull_request:
    branches:
    - master
    - 2.*

jobs:
  windows:
    name: Py${{ matrix.PYTHON_VERSION }}
    runs-on: windows-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'windows'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9']
    timeout-minutes: 25
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: true
           auto-activate-base: false
           channels: conda-forge
           miniforge-variant: Mambaforge
           python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install package dependencies
        shell: bash -l {0}
        run: mamba install --file requirements/windows.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          mamba install --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Set correct enconding
        shell: bash -l {0}
        if: matrix.PYTHON_VERSION == '2.7'
        run: echo "::set-env name=PYTHONIOENCODING::cp1252"
      - name: Run tests
        shell: bash -l {0}
        run: pytest spyder_kernels --cov=spyder_kernels -x -vv || pytest spyder_kernels --cov=spyder_kernels -x -vv || pytest spyder_kernels --cov=spyder_kernels -x -vv
