# -*- coding: utf-8 -*-
#
# Generated by ThemeWeaver
# Theme: Solarized
# Description: Based on the Solarized color palette by Ethan Schoonover, enhanced with a wider range of colors
# Author: Ethan Schoonover, adapted by the Spyder Team
# Version: 1.0.0

"""
Color palettes used by the Solarized theme in Spyder.
"""

class Primary:
    B0 = '#000000'
    B10 = '#002B36'
    B20 = '#003340'
    B30 = '#003D48'
    B40 = '#254750'
    B50 = '#315661'
    B60 = '#47676C'
    B70 = '#5C7878'
    B80 = '#8A9B93'
    B90 = '#A2ADA4'
    B100 = '#BABFB7'
    B110 = '#D4D3C6'
    B120 = '#E1DDCD'
    B130 = '#EEE8D5'
    B140 = '#FDF6E3'
    B150 = '#FFFFFF'


class Secondary:
    B0 = '#000000'
    B10 = '#0C3C49'
    B20 = '#145764'
    B30 = '#1D7B8A'
    B40 = '#329FAB'
    B50 = '#40B5BD'
    B60 = '#4FCBCF'
    B70 = '#5FE1E0'
    B80 = '#72E2E4'
    B90 = '#85E3E8'
    B100 = '#99E5EC'
    B110 = '#ADE8F0'
    B120 = '#C1EDF4'
    B130 = '#D7F2F8'
    B140 = '#EDF9FC'
    B150 = '#FFFFFF'


class Success:
    B0 = '#000000'
    B10 = '#064738'
    B20 = '#055C49'
    B30 = '#007A5E'
    B40 = '#008760'
    B50 = '#019D70'
    B60 = '#02BA85'
    B70 = '#20C997'
    B80 = '#44DEB0'
    B90 = '#3BEBB7'
    B100 = '#88F2D3'
    B110 = '#B0F5E1'
    B120 = '#D1FBEE'
    B130 = '#E4FFF7'
    B140 = '#F5FFFD'
    B150 = '#FFFFFF'


class Error:
    B0 = '#000000'
    B10 = '#470606'
    B20 = '#760B0B'
    B30 = '#AF0F0F'
    B40 = '#D4140B'
    B50 = '#DE321F'
    B60 = '#E24232'
    B70 = '#E74C3C'
    B80 = '#F66657'
    B90 = '#F88478'
    B100 = '#FFACA4'
    B110 = '#FFC3BD'
    B120 = '#FEDDDA'
    B130 = '#FFEEEE'
    B140 = '#FFF5F5'
    B150 = '#FFFFFF'


class Warning:
    B0 = '#000000'
    B10 = '#471D06'
    B20 = '#692907'
    B30 = '#AB3E00'
    B40 = '#CE4B01'
    B50 = '#E05E15'
    B60 = '#E57004'
    B70 = '#F37E12'
    B80 = '#FF993B'
    B90 = '#FFB950'
    B100 = '#FFCF84'
    B110 = '#FFDDA7'
    B120 = '#FFEACA'
    B130 = '#FFF3E2'
    B140 = '#FFFBF5'
    B150 = '#FFFFFF'


class GroupDark:
    B10 = '#EE3432'
    B20 = '#F19B00'
    B30 = '#A1C15E'
    B40 = '#00C5A8'
    B50 = '#8DC9E3'
    B60 = '#0053F1'
    B70 = '#8B56D1'
    B80 = '#BD2699'
    B90 = '#F7003D'
    B100 = '#C64900'
    B110 = '#D5B400'
    B120 = '#79D182'


class GroupLight:
    B10 = '#FF7564'
    B20 = '#FFC000'
    B30 = '#E1FF00'
    B40 = '#64E099'
    B50 = '#0ECCD4'
    B60 = '#0057B0'
    B70 = '#815EC4'
    B80 = '#B1379A'
    B90 = '#FF7683'
    B100 = '#FFB900'
    B110 = '#EFFB00'
    B120 = '#7CE6A4'


class Syntax:
    B10 = '#083f4d'
    B20 = '#073642'
    B30 = '#1A72BB'
    B40 = '#d33682'
    B50 = '#073642'
    B60 = '#586e75'
    B70 = '#dc322f'
    B80 = '#E1E1E1'
    B90 = '#859900'
    B100 = '#859900'
    B110 = '#6c71c4'
    B120 = '#268bd2'
    B130 = '#657b83'
    B140 = '#2aa198'
    B150 = '#d33682'
    B160 = '#b58900'


class SyntaxLight:
    B10 = '#f5efdB'
    B20 = '#eee8d5'
    B30 = '#C2E3FA'
    B40 = '#d33682'
    B50 = '#eee8d5'
    B60 = '#d6dabf'
    B70 = '#dc322f'
    B80 = '#657b83'
    B90 = '#859900'
    B100 = '#859900'
    B110 = '#6c71c4'
    B120 = '#268bd2'
    B130 = '#93a1a1'
    B140 = '#2aa198'
    B150 = '#d33682'
    B160 = '#b58900'


class Logos:
    B10 = '#3775a9'
    B20 = '#ffd444'
    B30 = '#414141'
    B40 = '#fafafa'
    B50 = '#ee0000'
