name: spy-inst
channels:
  - conda-forge
dependencies:
  - conda =24.9.2
  - conda-build =24.9.0
  - conda-lock =2.5.7
  - conda-standalone =24.9.2
  - constructor =3.10.0
  - gitpython
  - ruamel.yaml.jinja2
  - setuptools_scm
