import os
import qtawesome as qta
from spyderlib.qt.QtGui import QIcon

directory = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                             '../fonts')
qta.load_font('spyder', 'spyder.ttf', 'spyder-charmap.json', directory=directory)

_icons = {
    'configure':               qta.icon('fa.wrench'),
    'bold':                    qta.icon('fa.bold'),
    'italic':                  qta.icon('fa.italic'),
    'genprefs':                qta.icon('fa.cogs'),
    'exit':                    qta.icon('fa.power-off'),
    'run_small':               qta.icon('fa.play', color='green'),
    'syspath':                 qta.icon('fa.cogs'),
    'font':                    qta.icon('fa.font'),
    'tooloptions':             qta.icon('fa.cog'),
    'edit24':                  qta.icon('fa.edit'),
    'edit':                    qta.icon('fa.edit'),
    'filenew':                 qta.icon(['fa.file-o', 'fa.plus'], options=[{}, {'scale_factor': 0.5, 'offset': (0.0, 0.1)}]),
    'fileopen':                qta.icon('fa.folder-open'),
    'revert':                  qta.icon('fa.undo'),
    'filesave':                qta.icon('fa.save'),
    'save_all':                qta.icon(['fa.save', 'fa.save'], options=[{'offset': (-0.2, -0.2), 'scale_factor': 0.6}, {'offset': (0.2, 0.2), 'scale_factor': 0.6}]),
    'filesaveas':              qta.icon(['fa.save', 'fa.pencil'], options=[{'offset': (-0.2, -0.2), 'scale_factor': 0.6}, {'offset': (0.2, 0.2), 'scale_factor': 0.6}]),
    'print':                   qta.icon('fa.print'),          
    'fileclose':               qta.icon('fa.close'),
    'filecloseall':            qta.icon(['fa.close', 'fa.close', 'fa.close'], options=[{'scale_factor': 0.6, 'offset': (0.3, -0.3)}, {'scale_factor': 0.6, 'offset': (-0.3, -0.3)}, {'scale_factor': 0.6, 'offset': (0.3, 0.3)}]),
    'breakpoint_big':          qta.icon('fa.circle', color='darkred'),
    'breakpoint_cond_big':     qta.icon('fa.question-circle', color='darkred'),
    'debug':                   qta.icon('fa.bug', color='#3775a9'),
    'arrow-step-over':         qta.icon('spyder.step-forward', color='#3775a9'),
    'arrow-continue':          qta.icon('spyder.continue', color='#3775a9'),
    'arrow-step-in':           qta.icon('spyder.step-into', color='#3775a9'),
    'arrow-step-out':          qta.icon('spyder.step-out', color='#3775a9'),
    'stop_debug':              qta.icon('spyder.stop', color='#3775a9'),
    'run':                     qta.icon('spyder.run', color='green'),
    'run_settings':            qta.icon(['fa.wrench', 'spyder.run'], options=[{'offset':(-0.1, -0.1), 'scale_factor': 0.75}, {'offset': (0.0, 0.125), 'color': 'green','scale_factor': 0.75}]),
    'run_again':               qta.icon(['fa.repeat', 'spyder.run'], options=[{'offset':(-0.1, -0.1), 'scale_factor': 0.75}, {'offset':(0.1, 0.125), 'color': 'green', 'scale_factor': 0.75}]),
    'run_selection':           qta.icon('spyder.run-selection'),
    'run_cell':                qta.icon('spyder.run-one-inplace', color='green'),
    'run_cell_advance':        qta.icon('spyder.run-one', color='green'),
    'todo_list':               qta.icon(['fa.th-list', 'fa.check'], options=[{'color': '#3775a9'}, {'offset': (0.0, 0.2), 'color': 'orange', 'color_disabled': '#face7e'}]),
    'wng_list':                qta.icon(['fa.th-list', 'fa.warning'], options=[{'color': '#3775a9'}, {'offset': (0.0, 0.2), 'scale_factor': 0.75, 'color': 'orange', 'color_disabled': '#face7e'}]),
    'prev_wng':                qta.icon(['fa.arrow-left', 'fa.warning'], options=[{'color': '#3775a9'}, {'offset': (0.0, 0.2), 'scale_factor': 0.75, 'color': 'orange', 'color_disabled': '#face7e'}]),
    'next_wng':                qta.icon(['fa.arrow-right', 'fa.warning'], options=[{'color': '#3775a9'}, {'offset': (0.0, 0.2), 'scale_factor': 0.75, 'color': 'orange', 'color_disabled': '#face7e'}]),
    'last_edit_location':      qta.icon('fa.caret-up'),
    'prev_cursor':             qta.icon('fa.hand-o-left'),
    'next_cursor':             qta.icon('fa.hand-o-right'),
    'comment':                 qta.icon('fa.comment'),
    'indent':                  qta.icon('fa.indent'),
    'unindent':                qta.icon('fa.outdent'),
    'gotoline':                qta.icon('fa.sort-numeric-asc'),
    'error':                   qta.icon('fa.times-circle'),
    'warning':                 qta.icon('fa.warning'),
    'todo':                    qta.icon('fa.check', color='#3775a9'),
    'ipython_console':         qta.icon('spyder.ipython-logo'),
    'ipython_console_t':       qta.icon('spyder.ipython-logo', color='gray'),
    'python':                  qta.icon(['spyder.python-logo-up', 'spyder.python-logo-down'], options=[{'color': '#3775a9'}, {'color': '#ffd444'}]),
    'python_t':                qta.icon('spyder.python-logo', color='gray'),
    'terminated':              qta.icon('fa.circle'),
    'cmdprompt':               qta.icon('fa.terminal'),
    'cmdprompt_t':             qta.icon('fa.terminal', color='gray'),
    'console':                 qta.icon('fa.terminal'),
    'findf':                   qta.icon(['fa.file-o', 'fa.search'], options=[{'scale_factor': 1.0}, {'scale_factor': 0.6}]),
    'history24':               qta.icon('fa.history'),
    'history':                 qta.icon('fa.history'),
    'inspector':               qta.icon('fa.search'),
    'lock':                    qta.icon('fa.lock'),
    'lock_open':               qta.icon('fa.unlock-alt'),
    'outline_explorer':        qta.icon('spyder.treeview'),
    'project_expanded':        qta.icon('fa.plus'),
    'dictedit':                qta.icon('fa.th-list'),
    'previous':                qta.icon('fa.arrow-left'),
    'next':                    qta.icon('fa.arrow-right'),
    'set_workdir':             qta.icon('fa.check'),
    'up':                      qta.icon('fa.arrow-up'),
    'filesaveas2':             qta.icon(['fa.save', 'fa.close'], options=[{'scale_factor': 0.8, 'offset': (-0.1, -0.1)}, {'offset': (0.2, 0.2)}]),   # save_session_action
    'spyder_light':            qta.icon(['spyder.spyder-logo-background', 'spyder.spyder-logo-web'], options=[{'color': '#414141'}, {'color': '#fafafa'}]),
    'spyder':                  qta.icon(['spyder.spyder-logo-background', 'spyder.spyder-logo-web', 'spyder.spyder-logo-snake'], options=[{'color': '#414141'}, {'color': '#fafafa'}, {'color': '#ee0000'}]),
    'find':                    qta.icon('fa.search'),
    'findnext':                qta.icon(['fa.search', 'fa.long-arrow-down'], options=[{'scale_factor': 0.6, 'offset': (0.3, 0.0)}, {'offset': (-0.3, 0.0)}]),
    'findprevious':            qta.icon(['fa.search', 'fa.long-arrow-up'], options=[{'scale_factor': 0.6, 'offset': (0.3, 0.0)}, {'offset': (-0.3, 0.0)}]),
    'replace':                 qta.icon('fa.retweet'),
    'undo':                    qta.icon('fa.undo'),
    'redo':                    qta.icon('fa.repeat'),
    'editcopy':                qta.icon('fa.copy'),
    'editcut':                 qta.icon('fa.scissors'),
    'editpaste':               qta.icon('fa.clipboard'),
    'editdelete':              qta.icon('fa.eraser'),
    'selectall':               qta.icon('spyder.text-select-all'),
    'pythonpath_mgr':          qta.icon(['spyder.python-logo-up', 'spyder.python-logo-down'], options=[{'color': '#3775a9'}, {'color': '#ffd444'}]),
    'exit':                    qta.icon('fa.power-off'),
    'advanced':                qta.icon('fa.gear'),
    'bug':                     qta.icon('fa.bug'),
    'maximize':                qta.icon('spyder.maximize-pane'),
    'unmaximize':              qta.icon('spyder.minimize-pane'),
    'window_nofullscreen':     qta.icon('spyder.inward'),
    'window_fullscreen':       qta.icon('fa.arrows-alt'),
    'MessageBoxWarning':       qta.icon('fa.warning'),
    'arredit':                 qta.icon('fa.table'),
    'zoom_out':                qta.icon('fa.search-plus'),
    'home':                    qta.icon('fa.home'),
    'find':                    qta.icon('fa.search'),
    'plot':                    qta.icon('fa.line-chart'),
    'hist':                    qta.icon('fa.bar-chart'),
    'imshow':                  qta.icon('fa.image'),
    'insert':                  qta.icon('fa.sign-in'),
    'rename':                  qta.icon('fa.pencil'),
    'edit_add':                qta.icon('fa.copy'),
    'browse_tab':              qta.icon('fa.folder-o'),
    'filelist':                qta.icon('fa.list'), 
    'newwindow':               qta.icon('spyder.window'),
    'versplit':                qta.icon('spyder.rows'),
    'horsplit':                qta.icon('fa.columns'),
    'close_panel':             qta.icon('fa.close'),
    'class':                   qta.icon('spyder.circle-letter-c', color='#3775a9'),
    'private2':                qta.icon('fa.minus-circle', color='#7ea67e'),
    'private1':                qta.icon('fa.minus-circle', color='#7ea67e'),
    'method':                  qta.icon('spyder.circle-letter-m', color='green'),
    'function':                qta.icon('spyder.circle-letter-f', color='orange'),
    'blockcomment':            qta.icon('spyder.circle-hash', color='grey'),
    'cell':                    qta.icon('spyder.circle-percent', color='red'),
    'fromcursor':              qta.icon('fa.hand-o-right'),
    'filter':                  qta.icon('fa.filter'),
    'folder_new':              qta.icon(['fa.folder-o', 'fa.plus'], options=[{}, {'scale_factor': 0.5, 'offset': (0.0, 0.1)}]),
    'vcs_commit':              qta.icon('fa.check', color='green'),
    'vcs_browse':              qta.icon('fa.search', color='green'),
    'ArrowUp':                 qta.icon('fa.arrow-circle-up'),
    'kill':                    qta.icon('fa.warning'),
    'reload':                  qta.icon('fa.repeat'),
    'auto_reload':             qta.icon(['fa.repeat', 'fa.clock-o'], options=[{'scale_factor': 0.75, 'offset': (-0.1, -0.1)}, {'scale_factor': 0.5, 'offset': (0.25, 0.25)}]),
    'profiler':                qta.icon('fa.clock-o'),
    'fileimport':              qta.icon('fa.download'),
    'environ':                 qta.icon('fa.th-list'),
    'options_less':            qta.icon('fa.minus-square'),
    'options_more':            qta.icon('fa.plus-square'),
    'ArrowBack':               qta.icon('fa.arrow-circle-left'),
    'ArrowForward':            qta.icon('fa.arrow-circle-right'),
    'DialogApplyButton':       qta.icon('fa.check'),
    'DialogCloseButton':       qta.icon('fa.close'),
    'DialogHelpButton':        qta.icon('fa.question'),
    'DirClosedIcon':           qta.icon('fa.folder-o'),
    'DialogHelpButton':        qta.icon('fa.life-ring'),
    'MessageBoxInformation':   qta.icon('fa.info'),
    'DirOpenIcon':             qta.icon('fa.folder-open'),
    'FileIcon2':               qta.icon('fa.file-o'),   # QtHelper
    'DriveHDIcon':             qta.icon('fa.hdd-o'),
    'arrow':                   qta.icon('fa.arrow-right'),
    'collapse':                qta.icon('spyder.inward'),
    'expand':                  qta.icon('fa.arrows-alt'),
    'restore':                 qta.icon('fa.level-up'),
    'collapse_selection':      qta.icon('fa.minus-square-o'),
    'expand_selection':        qta.icon('fa.plus-square-o'),
    'copywop':                 qta.icon(['fa.terminal']),
    'editpaste':               qta.icon('fa.paste'),
    'editcopy':                qta.icon('fa.copy'),
    'edit':                    qta.icon('fa.edit'),
    'convention':              qta.icon('spyder.circle-letter-c', color='#3775a9'),
    'refactor':                qta.icon('spyder.circle-letter-r', color='#3775a9'),
}

def icon(name):
    return _icons.get(name, QIcon())
