package:
  name: spyder
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}  # [unix]
  version: 3.0.0b4  # [win]

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}  # [unix]
  number: 0  # [win]
  osx_is_app: True

source:
  fn:  spyder-3.0.0.dev0.zip  # [win]
  url: {{ ['file:///', environ.get('APPVEYOR_BUILD_FOLDER'), '\dist\spyder-3.0.0.dev0.zip']|join }}  # [win]
  git_url: {{ environ.get('FULL_SPYDER_CLONE') }}  # [unix]
  git_tag: {% if environ.get('TRAVIS_PULL_REQUEST') != 'false' %} {{ ['travis_pr_', environ.get('TRAVIS_PULL_REQUEST')]|join }} {% else %} master {% endif %}  # [unix]

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - python.app  # [osx]
    - {% if environ.get('USE_QT_API') == 'PyQt4' %} pyqt {% else %} pyqt5 {% endif %}
    - rope 0.9.*  # [py34 or py35]
    - rope  # [py27]
    - pyflakes
    - jedi
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - pylint
    - qtawesome
    - qtpy

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
