package:
  name: spyder-dev
  version: {{ GIT_DESCRIBE_TAG|replace('v', '') }}  # [unix]
  version: 99.99.0  # [win]

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}  # [unix]
  number: 0  # [win]

source:
  path: {{ APPVEYOR_BUILD_FOLDER }}  # [win]
  git_url: {{ FULL_SPYDER_CLONE }}  # [unix]

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - python.app  # [osx]
    - {% if environ.get('USE_QT_API') == 'PyQt4' %} qt 4.* {% else %} qt 5.* {% endif %}
    - {% if environ.get('USE_QT_API') == 'PyQt4' %} pyqt 4.* {% else %} pyqt 5.* {% endif %}
    - rope 0.9.*  # [py34 or py35]
    - rope  # [py27]
    - pyflakes
    - jedi
    - qtconsole
    - nbconvert
    - pygments
    - sphinx
    - pep8
    - psutil
    - pylint
    - qtawesome >=0.4
    - qtpy
    - chardet >=2.0.0
    - numpydoc

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
