name: spyder-remote
channels:
  - conda-forge  
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.12.*
  - pip
  - jupyter_server >=2.14.2,<3.0
  - jupyter_client >=8.6.2,<9.0
  - envs-manager <1.0.0
