name: Windows tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - '*'

concurrency:
  group: test-win-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Win Py${{ matrix.PYTHON_VERSION }}
    runs-on: windows-latest
    env:
      CI: 'true'
      OS: 'win'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.11', '3.10', '3.9']
    timeout-minutes: 10
    steps:
      - uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.PYTHON_VERSION }}-pip-
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: 'x64'
      - run: python -m pip install --upgrade pip setuptools
      - run: pip install -e .[all,test]
      - name: Show test environment
        run: pip list
      - run: pytest --color=yes -v test/
