#!/usr/bin/env python
import socket

from spyderlib.config import CONF

started = False
if CONF.get('main', 'started'):
    # In case Spyder dies while running, the 'started' value will be True
    # but the app will be closed, so we have to check if it's still
    # connected to the open_files_server port to be completely sure
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        #sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        port = CONF.get('main', 'open_files_port')
        sock.bind( ("127.0.0.1", port) )
        sock.close()
    except socket.error, _msg:  # analysis:ignore
        started = True

if not started:
    from spyderlib import spyder
    spyder.main()
else:
    from spyderlib import client
    client.main()
