# -*- coding: utf-8 -*-
#
# Copyright © Spyder Project Contributors
# Licensed under the terms of the MIT License
#

"""
Helpers used in widget tests
"""


SHORTCUTS = {
    'Close pane': ('Ctrl+Shift+F4' , u'⇧⌘F4'),
    'Configure': ('Ctrl+F6', u'⌘F6'),
    'Debug': ('Ctrl+F5', u'⌘F5'),
    'Debug continue': ('Ctrl+F12', u'⌘F12'),
    'Debug exit': ('Ctrl+Shift+F12', u'⇧⌘F12'),
    'Debug step into': ('Ctrl+F11', u'⌘F11'),
    'Debug step over': ('Ctrl+F10', u'⌘F10'),
    'Debug step return': ('Ctrl+Shift+F11', u'⇧⌘F11'),
    'File switcher': ('Ctrl+P', u'⌘P'),
    'Find next': ('F3', u'F3'),
    'Find previous': ('Shift+F3', u'⇧F3'),
    'Find text': ('Ctrl+F', u'⌘F'),
    'Fullscreen mode': ('F11', u'F11'),
    'Hide find and replace': ('Escape', u'⎋'),
    'Layout preferences': ('Shift+Alt+P', u'⌥⇧P'),
    'Lock unlock panes': ('Ctrl+Shift+F5', u'⇧⌘F5'),
    'Maximize pane': ('Ctrl+Alt+Shift+M', u'⌥⇧⌘M'),
    'Preferences': ('Ctrl+Alt+Shift+P', u'⌥⇧⌘P'),
    'Quit': ('Ctrl+Q', u'⌘Q'),
    'Re-run last script': ('F6', u'F6'),
    'Replace text': ('Ctrl+R', u'⌘R'),
    'Restart': ('Shift+Alt+R', u'⌥⇧R'),
    'Run': ('F5', u'F5'),
    'Save current layout': ('Shift+Alt+S', u'⌥⇧S'),
    'Show toolbars': ('Alt+Shift+T', u'⌥⇧T'),
    'Spyder documentation': ('F1', u'F1'),
    'Switch to breakpoints': ('Ctrl+Shift+B', u'⇧⌘B'),
    'Switch to editor': ('Ctrl+Shift+E', u'⇧⌘E'),
    'Switch to explorer': ('Ctrl+Shift+X', u'⇧⌘X'),
    'Switch to find in files': ('Ctrl+Shift+F', u'⇧⌘F'),
    'Switch to help': ('Ctrl+Shift+H', u'⇧⌘H'),
    'Switch to historylog': ('Ctrl+Shift+L', u'⇧⌘L'),
    'Switch to ipython console': ('Ctrl+Shift+I', u'⇧⌘I'),
    'Switch to onlinehelp': ('Ctrl+Shift+D', u'⇧⌘D'),
    'Switch to outline explorer': ('Ctrl+Shift+O', u'⇧⌘O'),
    'Switch to project explorer': ('Ctrl+Shift+P', u'⇧⌘P'),
    'Switch to variable explorer': ('Ctrl+Shift+V', u'⇧⌘V'),
    'Symbol finder': ('Ctrl+Alt+P', u'⌥⌘P'),
    'Use next layout': ('Shift+Alt+PgDown', u'⌥⇧⇟'),
    'Use previous layout': ('Shift+Alt+PgUp', u'⌥⇧⇞'),
    'Enter array inline': ('Ctrl+Alt+M', u'⌥⌘M'),
    'Enter array table': ('Ctrl+M', u'⌘M'),
    'Clear line': ('Shift+Escape', u'⇧⎋'),
    'Clear shell': ('Ctrl+L', u'⌘L'),
    'Inspect current object': ('Ctrl+I', u'⌘I'),
    'Blockcomment': ('Ctrl+4', u'⌘4'),
    'Breakpoint': ('F12', u'F12'),
    'Close all': ('Ctrl+Shift+W', u'⇧⌘W'),
    'Close file 1': ('Ctrl+W', u'⌘W'),
    'Close file 2': ('Ctrl+F4', u'⌘F4'),
    'Close split panel': ('Alt+Shift+W', u'⌥⇧W'),
    'Code completion': ('Meta+Space', u'⌃Space'),
    'Conditional breakpoint': ('Shift+F12', u'⇧F12'),
    'Copy': ('Ctrl+C', u'⌘C'),
    'Copy line': ('Shift+Alt+Down', u'⌥⇧↓'),
    'Cut': ('Ctrl+X', u'⌘X'),
    'Cycle to next file': ('Ctrl+PgDown', u'⌘⇟'),
    'Cycle to previous file': ('Ctrl+PgUp', u'⌘⇞'),
    'Delete': ('Del', u'⌦'),
    'Delete line': ('Ctrl+D', u'⌘D'),
    'Duplicate line': ('Shift+Alt+Up', u'⌥⇧↑'),
    'End of document': ('Ctrl+End', u'⌘↘'),
    'End of line': ('Meta+E', u'⌃E'),
    'Go to definition': ('Ctrl+G', u'⌘G'),
    'Go to line': ('Ctrl+L', u'⌘L'),
    'Go to new line': ('Ctrl+Shift+Return', u'⇧⌘↵'),
    'Go to next cell': ('Ctrl+Down', u'⌘↓'),
    'Go to next file': ('Ctrl+Tab', u'⌘⇥'),
    'Go to previous cell': ('Ctrl+Up', u'⌘↑'),
    'Go to previous file': ('Ctrl+Shift+Tab', u'⇧⌘⇥'),
    'Indent': ('Ctrl+]', u'⌘]'),
    'Inspect current object': ('Ctrl+I', u'⌘I'),
    'Kill next word': ('Meta+D', u'⌃D'),
    'Kill previous word': ('Meta+Backspace', u'⌃⌫'),
    'Kill to line end': ('Meta+K', u'⌃K'),
    'Kill to line start': ('Meta+U', u'⌃U'),
    'Last edit location': ('Ctrl+Alt+Shift+Left', u'⌥⇧⌘←'),
    'Move line down': ('Alt+Down', u'⌥↓'),
    'Move line up': ('Alt+Up', u'⌥↑'),
    'New file': ('Ctrl+N', u'⌘N'),
    'Next char': ('Meta+F', u'⌃F'),
    'Next cursor position': ('Ctrl+Alt+Right', u'⌥⌘→'),
    'Next line': ('Meta+N', u'⌃N'),
    'Next warning': ('Ctrl+Alt+Shift+.', u'⌥⇧⌘.'),
    'Next word': ('Ctrl+Right', u'⌘→'),
    'Open file': ('Ctrl+O', u'⌘O'),
    'Open last closed': ('Ctrl+Shift+T', u'⇧⌘T'),
    'Paste': ('Ctrl+V', u'⌘V'),
    'Previous char': ('Meta+B', u'⌃B'),
    'Previous cursor position': ('Ctrl+Alt+Left', u'⌥⌘←'),
    'Previous line': ('Meta+P', u'⌃P'),
    'Previous warning': ('Ctrl+Alt+Shift+,', u'⌥⇧⌘,'),
    'Previous word': ('Ctrl+Left', u'⌘←'),
    'Re-run last cell': ('Alt+Return', u'⌥↵'),
    'Redo': ('Ctrl+Shift+Z', u'⇧⌘Z'),
    'Rotate kill ring': ('Shift+Meta+Y', u'⌃⇧Y'),
    'Run cell': ('Meta+Return', u'⌃↵'),
    'Run cell and advance': ('Shift+Return', u'⇧↵'),
    'Run selection': ('F9', u'F9'),
    'Save all': ('Ctrl+Alt+S', u'⌥⌘S'),
    'Save as': ('Ctrl+Shift+S', u'⇧⌘S'),
    'Save file': ('Ctrl+S', u'⌘S'),
    'Select all': ('Ctrl+A', u'⌘A'),
    'Split horizontally': ('Ctrl+_', u'⌘_'),
    'Split vertically': ('Ctrl+{', u'⌘{'),
    'Start of document': ('Ctrl+Home', u'⌘↖'),
    'Start of line': ('Meta+A', u'⌃A'),
    'Toggle comment': ('Ctrl+1', u'⌘1'),
    'Transform to lowercase': ('Ctrl+U', u'⌘U'),
    'Transform to uppercase': ('Ctrl+Shift+U', u'⇧⌘U'),
    'Unblockcomment': ('Ctrl+5', u'⌘5'),
    'Undo': ('Ctrl+Z', u'⌘Z'),
    'Unindent': ('Ctrl+[', u'⌘['),
    'Yank': ('Meta+Y', u'⌃Y'),
    'Zoom in 1': ('Ctrl++', u'⌘+'),
    'Zoom in 2': ('Ctrl+=', u'⌘='),
    'Zoom out': ('Ctrl+-', u'⌘-'),
    'Zoom reset': ('Ctrl+0', u'⌘0'),
    'New tab': ('Ctrl+T', u'⌘T'),
    'Reset namespace': ('Ctrl+Alt+R', u'⌥⌘R'),
    'Restart kernel': ('Ctrl+.', u'⌘.'),
    'Run profiler': ('F10', u'F10'),
    'Run analysis': ('F8', u'F8'),
    'Copy': ('Ctrl+C', u'⌘C'),
}
