# -*- coding: utf-8 -*-
#
# Copyright © Spyder Project Contributors
# Licensed under the terms of the MIT License
#

"""
Helpers used in widget tests
"""


SHORTCUTS = {
    'Close pane': ('Shift+Ctrl+F4' ,'⇧⌘F4'),
    'Configure': ('Ctrl+F6', '⌘F6'),
    'Debug': ('Ctrl+F5', '⌘F5'),
    'Debug continue': ('Ctrl+F12', '⌘F12'),
    'Debug exit': ('Ctrl+Shift+F12', '⇧⌘F12'),
    'Debug step into': ('Ctrl+F11', '⌘F11'),
    'Debug step over': ('Ctrl+F10', '⌘F10'),
    'Debug step return': ('Ctrl+Shift+F11', '⇧⌘F11'),
    'File switcher': ('Ctrl+P', '⌘P'),
    'Find next': ('F3', 'F3'),
    'Find previous': ('Shift+F3', '⇧F3'),
    'Find text': ('Ctrl+F', '⌘F'),
    'Fullscreen mode': ('F11', 'F11'),
    'Hide find and replace': ('Escape', '⎋'),
    'Layout preferences': ('Shift+Alt+P', '⌥⇧P'),
    'Lock unlock panes': ('Shift+Ctrl+F5', '⇧⌘F5'),
    'Maximize pane': ('Ctrl+Alt+Shift+M', '⌥⇧⌘M'),
    'Preferences': ('Ctrl+Alt+Shift+P', '⌥⇧⌘P'),
    'Quit': ('Ctrl+Q', '⌘Q'),
    'Re-run last script': ('F6', 'F6'),
    'Replace text': ('Ctrl+R', '⌘R'),
    'Restart': ('Shift+Alt+R', '⌥⇧R'),
    'Run': ('F5', 'F5'),
    'Save current layout': ('Shift+Alt+S', '⌥⇧S'),
    'Show toolbars': ('Alt+Shift+T', '⌥⇧T'),
    'Spyder documentation': ('F1', 'F1'),
    'Switch to breakpoints': ('Ctrl+Shift+B', '⇧⌘B'),
    'Switch to editor': ('Ctrl+Shift+E', '⇧⌘E'),
    'Switch to explorer': ('Ctrl+Shift+X', '⇧⌘X'),
    'Switch to find in files': ('Ctrl+Shift+F', '⇧⌘F'),
    'Switch to help': ('Ctrl+Shift+H', '⇧⌘H'),
    'Switch to historylog': ('Ctrl+Shift+L', '⇧⌘L'),
    'Switch to ipython console': ('Ctrl+Shift+I', '⇧⌘I'),
    'Switch to onlinehelp': ('Ctrl+Shift+D', '⇧⌘D'),
    'Switch to outline explorer': ('Ctrl+Shift+O', '⇧⌘O'),
    'Switch to project explorer': ('Ctrl+Shift+P', '⇧⌘P'),
    'Switch to variable explorer': ('Ctrl+Shift+V', '⇧⌘V'),
    'Symbol finder': ('Ctrl+Alt+P', '⌥⌘P'),
    'Use next layout': ('Shift+Alt+PgDown', '⌥⇧⇟'),
    'Use previous layout': ('Shift+Alt+PgUp', '⌥⇧⇞'),
    'Enter array inline': ('Ctrl+Alt+M', '⌥⌘M'),
    'Enter array table': ('Ctrl+M', '⌘M'),
    'Clear line': ('Shift+Escape', '⇧⎋'),
    'Clear shell': ('Ctrl+L', '⌘L'),
    'Inspect current object': ('Ctrl+I', '⌘I'),
    'Blockcomment': ('Ctrl+4', '⌘4'),
    'Breakpoint': ('F12', 'F12'),
    'Close all': ('Ctrl+Shift+W', '⇧⌘W'),
    'Close file 1': ('Ctrl+W', '⌘W'),
    'Close file 2': ('Ctrl+F4', '⌘F4'),
    'Close split panel': ('Alt+Shift+W', '⌥⇧W'),
    'Code completion': ('Meta+Space', '⌃Space'),
    'Conditional breakpoint': ('Shift+F12', '⇧F12'),
    'Copy': ('Ctrl+C', '⌘C'),
    'Copy line': ('Shift+Alt+Down', '⌥⇧↓'),
    'Cut': ('Ctrl+X', '⌘X'),
    'Cycle to next file': ('Ctrl+PgDown', '⌘⇟'),
    'Cycle to previous file': ('Ctrl+PgUp', '⌘⇞'),
    'Delete': ('Del', '⌦'),
    'Delete line': ('Ctrl+D', '⌘D'),
    'Duplicate line': ('Shift+Alt+Up', '⌥⇧↑'),
    'End of document': ('Ctrl+End', '⌘↘'),
    'End of line': ('Meta+E', '⌃E'),
    'Go to definition': ('Ctrl+G', '⌘G'),
    'Go to line': ('Ctrl+L', '⌘L'),
    'Go to new line': ('Ctrl+Shift+Return', '⇧⌘↵'),
    'Go to next cell': ('Ctrl+Down', '⌘↓'),
    'Go to next file': ('Ctrl+Tab', '⌘⇥'),
    'Go to previous cell': ('Ctrl+Up', '⌘↑'),
    'Go to previous file': ('Ctrl+Shift+Tab', '⇧⌘⇥'),
    'Indent': ('Ctrl+]', '⌘]'),
    'Inspect current object': ('Ctrl+I', '⌘I'),
    'Kill next word': ('Meta+D', '⌃D'),
    'Kill previous word': ('Meta+Backspace', '⌃⌫'),
    'Kill to line end': ('Meta+K', '⌃K'),
    'Kill to line start': ('Meta+U', '⌃U'),
    'Last edit location': ('Ctrl+Alt+Shift+Left', '⌥⇧⌘←'),
    'Move line down': ('Alt+Down', '⌥↓'),
    'Move line up': ('Alt+Up', '⌥↑'),
    'New file': ('Ctrl+N', '⌘N'),
    'Next char': ('Meta+F', '⌃F'),
    'Next cursor position': ('Ctrl+Alt+Right', '⌥⌘→'),
    'Next line': ('Meta+N', '⌃N'),
    'Next warning': ('Ctrl+Alt+Shift+.', '⌥⇧⌘.'),
    'Next word': ('Ctrl+Right', '⌘→'),
    'Open file': ('Ctrl+O', '⌘O'),
    'Open last closed': ('Ctrl+Shift+T', '⇧⌘T'),
    'Paste': ('Ctrl+V', '⌘V'),
    'Previous char': ('Meta+B', '⌃B'),
    'Previous cursor position': ('Ctrl+Alt+Left', '⌥⌘←'),
    'Previous line': ('Meta+P', '⌃P'),
    'Previous warning': ('Ctrl+Alt+Shift+,', '⌥⇧⌘,'),
    'Previous word': ('Ctrl+Left', '⌘←'),
    'Re-run last cell': ('Alt+Return', '⌥↵'),
    'Redo': ('Ctrl+Shift+Z', '⇧⌘Z'),
    'Rotate kill ring': ('Shift+Meta+Y', '⌃⇧Y'),
    'Run cell': ('Meta+Return', '⌃↵'),
    'Run cell and advance': ('Shift+Return', '⇧↵'),
    'Run selection': ('F9', 'F9'),
    'Save all': ('Ctrl+Alt+S', '⌥⌘S'),
    'Save as': ('Ctrl+Shift+S', '⇧⌘S'),
    'Save file': ('Ctrl+S', '⌘S'),
    'Select all': ('Ctrl+A', '⌘A'),
    'Split horizontally': ('Ctrl+_', '⌘_'),
    'Split vertically': ('Ctrl+{', '⌘{'),
    'Start of document': ('Ctrl+Home', '⌘↖'),
    'Start of line': ('Meta+A', '⌃A'),
    'Toggle comment': ('Ctrl+1', '⌘1'),
    'Transform to lowercase': ('Ctrl+U', '⌘U'),
    'Transform to uppercase': ('Ctrl+Shift+U', '⇧⌘U'),
    'Unblockcomment': ('Ctrl+5', '⌘5'),
    'Undo': ('Ctrl+Z', '⌘Z'),
    'Unindent': ('Ctrl+[', '⌘['),
    'Yank': ('Meta+Y', '⌃Y'),
    'Zoom in 1': ('Ctrl++', '⌘+'),
    'Zoom in 2': ('Ctrl+=', '⌘='),
    'Zoom out': ('Ctrl+-', '⌘-'),
    'Zoom reset': ('Ctrl+0', '⌘0'),
    'New tab': ('Ctrl+T', '⌘T'),
    'Reset namespace': ('Ctrl+Alt+R', '⌥⌘R'),
    'Restart kernel': ('Ctrl+.', '⌘.'),
    'Run profiler': ('F10', 'F10'),
    'Run analysis': ('F8', 'F8'),
    'Copy': ('Ctrl+C', '⌘C'),
}
