environment:
  global:
    APPVEYOR_RDP_PASSWORD: "dcca4c4863E30d56c2e0dda6327370b3#"
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.7"
      PYTHON_ARCH: "64"

matrix:
  fast_finish: true

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/python.exe -m pip install --upgrade pip setuptools"
  - "%PYTHON%/python.exe -m pip install .[all] .[test]"

test_script:
  - "%PYTHON%/Scripts/pytest.exe -v test/"

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: false  # Not a C# project

cache:
  - '%APPDATA%\pip\Cache'
