# -*- coding: utf-8 -*-
#
# Generated by ThemeWeaver
# Theme: Dracula
# Description: Based on the Dracula color palette by Zeno Rocha
# Author: Zeno Rocha and Luxonauta, adapted and extended by Spyder Team
# Version: 1.0.0

"""
Color palettes used by the Dracula theme in Spyder.
"""

class Primary:
    B0 = '#000000'
    B10 = '#282A36'
    B20 = '#2B2D39'
    B30 = '#353741'
    B40 = '#44454F'
    B50 = '#565860'
    B60 = '#6C6D73'
    B70 = '#848588'
    B80 = '#9B9C9E'
    B90 = '#B3B4B3'
    B100 = '#C9C9C6'
    B110 = '#DBDCD7'
    B120 = '#EAEAE5'
    B130 = '#F4F4ED'
    B140 = '#F8F8F1'
    B150 = '#FFFFFF'


class Secondary:
    B0 = '#000000'
    B10 = '#13090E'
    B20 = '#2B1923'
    B30 = '#452637'
    B40 = '#61334D'
    B50 = '#7E4063'
    B60 = '#9C4E7B'
    B70 = '#BC5C93'
    B80 = '#DD6AAC'
    B90 = '#FE79C6'
    B100 = '#FD79C6'
    B110 = '#FF99D4'
    B120 = '#FFB7E1'
    B130 = '#FFD4ED'
    B140 = '#FEF0F9'
    B150 = '#FFFFFF'


class Success:
    B0 = '#000000'
    B10 = '#064738'
    B20 = '#055C49'
    B30 = '#007A5E'
    B40 = '#008760'
    B50 = '#019D70'
    B60 = '#02BA85'
    B70 = '#20C997'
    B80 = '#44DEB0'
    B90 = '#3BEBB7'
    B100 = '#88F2D3'
    B110 = '#B0F5E1'
    B120 = '#D1FBEE'
    B130 = '#E4FFF7'
    B140 = '#F5FFFD'
    B150 = '#FFFFFF'


class Error:
    B0 = '#000000'
    B10 = '#470606'
    B20 = '#760B0B'
    B30 = '#AF0F0F'
    B40 = '#D4140B'
    B50 = '#DE321F'
    B60 = '#E24232'
    B70 = '#E74C3C'
    B80 = '#F66657'
    B90 = '#F88478'
    B100 = '#FFACA4'
    B110 = '#FFC3BD'
    B120 = '#FEDDDA'
    B130 = '#FFEEEE'
    B140 = '#FFF5F5'
    B150 = '#FFFFFF'


class Warning:
    B0 = '#000000'
    B10 = '#471D06'
    B20 = '#692907'
    B30 = '#AB3E00'
    B40 = '#CE4B01'
    B50 = '#E05E15'
    B60 = '#E57004'
    B70 = '#F37E12'
    B80 = '#FF993B'
    B90 = '#FFB950'
    B100 = '#FFCF84'
    B110 = '#FFDDA7'
    B120 = '#FFEACA'
    B130 = '#FFF3E2'
    B140 = '#FFFBF5'
    B150 = '#FFFFFF'


class GroupDark:
    B10 = '#EE3432'
    B20 = '#F19B00'
    B30 = '#A1C15E'
    B40 = '#00C5A8'
    B50 = '#8DC9E3'
    B60 = '#0053F1'
    B70 = '#8B56D1'
    B80 = '#BD2699'
    B90 = '#F7003D'
    B100 = '#C64900'
    B110 = '#D5B400'
    B120 = '#79D182'


class GroupLight:
    B10 = '#FF7564'
    B20 = '#FFC000'
    B30 = '#E1FF00'
    B40 = '#64E099'
    B50 = '#0ECCD4'
    B60 = '#0057B0'
    B70 = '#815EC4'
    B80 = '#B1379A'
    B90 = '#FF7683'
    B100 = '#FFB900'
    B110 = '#EFFB00'
    B120 = '#7CE6A4'


class Logos:
    B10 = '#3775a9'
    B20 = '#ffd444'
    B30 = '#414141'
    B40 = '#fafafa'
    B50 = '#ee0000'
