# -*- coding: utf-8 -*-
#
# Generated by ThemeWeaver
# Theme: Dracula
# Description: Based on the Dracula color palette by Zeno Rocha
# Author: Zeno Rocha and Luxonauta, adapted and extended by Spyder Team
# Version: 1.0.0

"""
Color palettes used by the Dracula theme in Spyder.
"""

class Primary:
    B0 = '#000000'
    B10 = '#121216'
    B20 = '#1D1E25'
    B30 = '#282A36'
    B40 = '#373844'
    B50 = '#474853'
    B60 = '#575863'
    B70 = '#686973'
    B80 = '#7A7A83'
    B90 = '#8B8C94'
    B100 = '#9E9EA5'
    B110 = '#B0B1B6'
    B120 = '#C3C4C8'
    B130 = '#D7D7DA'
    B140 = '#EAEBEC'
    B150 = '#FFFFFF'


class Secondary:
    B0 = '#000000'
    B10 = '#1C1217'
    B20 = '#311D27'
    B30 = '#472739'
    B40 = '#5F324B'
    B50 = '#773D5E'
    B60 = '#914971'
    B70 = '#AB5485'
    B80 = '#C6609A'
    B90 = '#E26CB0'
    B100 = '#FF79C6'
    B110 = '#FE98D0'
    B120 = '#FEB3DB'
    B130 = '#FECDE6'
    B140 = '#FEE6F2'
    B150 = '#FFFFFF'


class Success:
    B0 = '#000000'
    B10 = '#0E170E'
    B20 = '#162617'
    B30 = '#1C3620'
    B40 = '#224728'
    B50 = '#285930'
    B60 = '#2D6B39'
    B70 = '#337E42'
    B80 = '#38924B'
    B90 = '#3DA654'
    B100 = '#42BA5D'
    B110 = '#46CF67'
    B120 = '#4BE471'
    B130 = '#50FA7B'
    B140 = '#B6FEBD'
    B150 = '#FFFFFF'


class Error:
    B0 = '#000000'
    B10 = '#20100E'
    B20 = '#371917'
    B30 = '#50221F'
    B40 = '#6B2A28'
    B50 = '#863330'
    B60 = '#A33B39'
    B70 = '#C14442'
    B80 = '#DF4C4B'
    B90 = '#FF5555'
    B100 = '#FE7A72'
    B110 = '#FE988F'
    B120 = '#FEB4AC'
    B130 = '#FECDC8'
    B140 = '#FEE6E3'
    B150 = '#FFFFFF'


class Warning:
    B0 = '#000000'
    B10 = '#19130E'
    B20 = '#2A2017'
    B30 = '#3C2D1E'
    B40 = '#4F3B26'
    B50 = '#63492E'
    B60 = '#775737'
    B70 = '#8D673F'
    B80 = '#A27648'
    B90 = '#B98650'
    B100 = '#CF9659'
    B110 = '#E7A762'
    B120 = '#FFB86C'
    B130 = '#FED0A4'
    B140 = '#FEE7D3'
    B150 = '#FFFFFF'


class GroupDark:
    B10 = '#EE3432'
    B20 = '#3CB7FE'
    B30 = '#5F8600'
    B40 = '#9D5782'
    B50 = '#00B9C2'
    B60 = '#E18100'
    B70 = '#0161D8'
    B80 = '#02A056'
    B90 = '#FE8B9B'
    B100 = '#0583A5'
    B110 = '#797118'
    B120 = '#C996D1'


class GroupLight:
    B10 = '#FE5448'
    B20 = '#0190CE'
    B30 = '#486600'
    B40 = '#6D485E'
    B50 = '#3C8E93'
    B60 = '#B06400'
    B70 = '#0149A7'
    B80 = '#027C41'
    B90 = '#FE306A'
    B100 = '#00647F'
    B110 = '#5B5529'
    B120 = '#957A9A'


class Syntax:
    B10 = '#30323F'
    B20 = '#44475A'
    B30 = '#6272A4'
    B40 = '#F8F8F2'
    B50 = '#30323F'
    B60 = '#8BE9FD'
    B70 = '#FF5555'
    B80 = '#F8F8F2'
    B90 = '#FF79C6'
    B100 = '#FFB86C'
    B110 = '#BD93F9'
    B120 = '#50FA7B'
    B130 = '#6272A4'
    B140 = '#F1FA8C'
    B150 = '#BD93F9'
    B160 = '#F8F8F2'


class SyntaxLight:
    B10 = '#e6e6e6'
    B20 = '#dcdcdc'
    B30 = '#8be9fd'
    B40 = '#282a36'
    B50 = '#f0f0f0'
    B60 = '#50fa7b'
    B70 = '#ff5555'
    B80 = '#282a36'
    B90 = '#ff79c6'
    B100 = '#ffb86c'
    B110 = '#bd93f9'
    B120 = '#50fa7b'
    B130 = '#7e869a'
    B140 = '#f1fa8c'
    B150 = '#bd93f9'
    B160 = '#282a36'


class Logos:
    B10 = '#3775a9'
    B20 = '#ffd444'
    B30 = '#414141'
    B40 = '#fafafa'
    B50 = '#ee0000'
