# -*- coding: utf-8 -*-
#
# Generated by ThemeWeaver
# Theme: Dracula
# Description: Based on the Dracula color palette by Zeno Rocha
# Author: Zeno Rocha and Luxonauta, adapted and extended by Spyder Team
# Version: 1.0.0

"""
Palettes for Dracula theme used in Spyder.
"""

# Standard library imports
from collections import OrderedDict

# Local imports
from spyder.config.gui import is_dark_interface
from .colorsystem import Primary, Secondary, Success, Error, Warning, GroupDark, GroupLight, Logos

# Theme ID
THEME_ID = "dracula"

# =============================================================================
# ---- Base Palette class
# =============================================================================

class Palette(object):
    """Base palette mixin."""

    ID = None

    # Color
    COLOR_BACKGROUND_1 = ''
    COLOR_BACKGROUND_2 = ''
    COLOR_BACKGROUND_3 = ''
    COLOR_BACKGROUND_4 = ''
    COLOR_BACKGROUND_5 = ''
    COLOR_BACKGROUND_6 = ''

    COLOR_TEXT_1 = ''
    COLOR_TEXT_2 = ''
    COLOR_TEXT_3 = ''
    COLOR_TEXT_4 = ''

    COLOR_ACCENT_1 = ''
    COLOR_ACCENT_2 = ''
    COLOR_ACCENT_3 = ''
    COLOR_ACCENT_4 = ''
    COLOR_ACCENT_5 = ''

    COLOR_DISABLED = ''

    OPACITY_TOOLTIP = 0

    # Size
    SIZE_BORDER_RADIUS = '4px'

    # Borders
    BORDER_1 = "1px solid $COLOR_BACKGROUND_1"
    BORDER_2 = "1px solid $COLOR_BACKGROUND_4"
    BORDER_3 = "1px solid $COLOR_BACKGROUND_6"

    BORDER_SELECTION_3 = "1px solid $COLOR_ACCENT_3"
    BORDER_SELECTION_2 = "1px solid $COLOR_ACCENT_2"
    BORDER_SELECTION_1 = "1px solid $COLOR_ACCENT_1"

    # Example of additional widget specific variables
    W_STATUS_BAR_BACKGROUND_COLOR = COLOR_ACCENT_1

    # Paths
    PATH_RESOURCES = "':/qss_icons'"

    @classmethod
    def to_dict(cls, colors_only=False):
        """Convert variables to dictionary."""
        order = [
            'ID',
            'COLOR_BACKGROUND_6',
            'COLOR_BACKGROUND_5',
            'COLOR_BACKGROUND_4',
            'COLOR_BACKGROUND_2',
            'COLOR_BACKGROUND_3',
            'COLOR_BACKGROUND_1',
            'COLOR_TEXT_1',
            'COLOR_TEXT_2',
            'COLOR_TEXT_3',
            'COLOR_TEXT_4',
            'COLOR_ACCENT_1',
            'COLOR_ACCENT_2',
            'COLOR_ACCENT_3',
            'COLOR_ACCENT_4',
            'COLOR_ACCENT_5',
            'COLOR_DISABLED',
            'OPACITY_TOOLTIP',
            'SIZE_BORDER_RADIUS',
            'BORDER_1',
            'BORDER_2',
            'BORDER_3',
            'BORDER_SELECTION_3',
            'BORDER_SELECTION_2',
            'BORDER_SELECTION_1',
            'W_STATUS_BAR_BACKGROUND_COLOR',
            'PATH_RESOURCES',
        ]
        dic = OrderedDict()
        for var in order:
            value = getattr(cls, var)

            if var == 'ID':
                value = "'{}'".format(value)

            if colors_only:
                if not var.startswith('COLOR'):
                    value = None

            if value:
                dic[var] = value

        return dic

    @classmethod
    def color_palette(cls):
        """Return the ordered colored palette dictionary."""
        return cls.to_dict(colors_only=True)

    @staticmethod
    def from_dict(class_values, class_name="FromDictPalette"):
        """Return palette class definition from dictionary."""
        return type(class_name, (Palette, ), class_values)

# =============================================================================
# ---- Dracula palettes
# =============================================================================

class SpyderPaletteDark(Palette):
    """Dark palette for Dracula."""

    ID = "dark"
    # Background colors
    COLOR_BACKGROUND_1 = Primary.B10
    COLOR_BACKGROUND_2 = Primary.B20
    COLOR_BACKGROUND_3 = Primary.B30
    COLOR_BACKGROUND_4 = Primary.B40
    COLOR_BACKGROUND_5 = Primary.B50
    COLOR_BACKGROUND_6 = Primary.B60
    # Text colors
    COLOR_TEXT_1 = Primary.B130
    COLOR_TEXT_2 = Primary.B120
    COLOR_TEXT_3 = Primary.B110
    COLOR_TEXT_4 = Primary.B100
    # Accent colors
    COLOR_ACCENT_1 = Secondary.B10
    COLOR_ACCENT_2 = Secondary.B20
    COLOR_ACCENT_3 = Secondary.B30
    COLOR_ACCENT_4 = Secondary.B40
    COLOR_ACCENT_5 = Secondary.B50
    # Disabled elements
    COLOR_DISABLED = Primary.B70
    # Success colors
    COLOR_SUCCESS_1 = Success.B40
    COLOR_SUCCESS_2 = Success.B70
    COLOR_SUCCESS_3 = Success.B90
    # Error colors
    COLOR_ERROR_1 = Error.B40
    COLOR_ERROR_2 = Error.B80
    COLOR_ERROR_3 = Error.B110
    # Warning colors
    COLOR_WARN_1 = Warning.B40
    COLOR_WARN_2 = Warning.B70
    COLOR_WARN_3 = Warning.B90
    COLOR_WARN_4 = Warning.B100
    # Icon colors
    ICON_1 = Primary.B140
    ICON_2 = Secondary.B80
    ICON_3 = Success.B80
    ICON_4 = Error.B70
    ICON_5 = Warning.B70
    ICON_6 = Primary.B30
    ICON_7 = GroupDark.B90
    # Group colors
    GROUP_1 = GroupDark.B10
    GROUP_2 = GroupDark.B20
    GROUP_3 = GroupDark.B30
    GROUP_4 = GroupDark.B40
    GROUP_5 = GroupDark.B50
    GROUP_6 = GroupDark.B60
    GROUP_7 = GroupDark.B70
    GROUP_8 = GroupDark.B80
    GROUP_9 = GroupDark.B90
    GROUP_10 = GroupDark.B100
    GROUP_11 = GroupDark.B110
    GROUP_12 = GroupDark.B120
    # Highlight colors
    COLOR_HIGHLIGHT_1 = Secondary.B10
    COLOR_HIGHLIGHT_2 = Secondary.B20
    COLOR_HIGHLIGHT_3 = Secondary.B30
    COLOR_HIGHLIGHT_4 = Secondary.B50
    # Occurrence colors
    COLOR_OCCURRENCE_1 = Primary.B10
    COLOR_OCCURRENCE_2 = Primary.B20
    COLOR_OCCURRENCE_3 = Primary.B30
    COLOR_OCCURRENCE_4 = Primary.B50
    COLOR_OCCURRENCE_5 = Primary.B80
    # Logo colors
    PYTHON_LOGO_UP = Logos.B10
    PYTHON_LOGO_DOWN = Logos.B20
    SPYDER_LOGO_BACKGROUND = Logos.B30
    SPYDER_LOGO_WEB = Logos.B40
    SPYDER_LOGO_SNAKE = Logos.B50
    # Special tabs
    SPECIAL_TABS_SEPARATOR = Primary.B70
    SPECIAL_TABS_SELECTED = Secondary.B20
    # For the heart used to ask for donations
    COLOR_HEART = Secondary.B80
    # For editor tooltips
    TIP_TITLE_COLOR = Success.B80
    TIP_CHAR_HIGHLIGHT_COLOR = Warning.B90
    # Tooltip opacity (numeric value, not a color reference)
    OPACITY_TOOLTIP = 230

    # Border radius
    SIZE_BORDER_RADIUS = '4px'

    # Borders
    BORDER_1 = "1px solid $COLOR_BACKGROUND_1"
    BORDER_2 = "1px solid $COLOR_BACKGROUND_4"
    BORDER_3 = "1px solid $COLOR_BACKGROUND_6"

    BORDER_SELECTION_3 = "1px solid $COLOR_ACCENT_3"
    BORDER_SELECTION_2 = "1px solid $COLOR_ACCENT_2"
    BORDER_SELECTION_1 = "1px solid $COLOR_ACCENT_1"

    # Widget specific variables
    W_STATUS_BAR_BACKGROUND_COLOR = COLOR_ACCENT_1

    # Paths
    PATH_RESOURCES = "':/qss_icons'"


class SpyderPaletteLight(Palette):
    """Light palette for Dracula."""

    ID = "light"
    # Background colors
    COLOR_BACKGROUND_1 = Primary.B140
    COLOR_BACKGROUND_2 = Primary.B130
    COLOR_BACKGROUND_3 = Primary.B120
    COLOR_BACKGROUND_4 = Primary.B110
    COLOR_BACKGROUND_5 = Primary.B100
    COLOR_BACKGROUND_6 = Primary.B90
    # Text colors
    COLOR_TEXT_1 = Primary.B20
    COLOR_TEXT_2 = Primary.B30
    COLOR_TEXT_3 = Primary.B50
    COLOR_TEXT_4 = Primary.B70
    # Accent colors
    COLOR_ACCENT_1 = Secondary.B70
    COLOR_ACCENT_2 = Secondary.B60
    COLOR_ACCENT_3 = Secondary.B50
    COLOR_ACCENT_4 = Secondary.B40
    COLOR_ACCENT_5 = Secondary.B30
    # Disabled elements
    COLOR_DISABLED = Primary.B60
    # Success colors
    COLOR_SUCCESS_1 = Success.B40
    COLOR_SUCCESS_2 = Success.B70
    COLOR_SUCCESS_3 = Success.B30
    # Error colors
    COLOR_ERROR_1 = Error.B40
    COLOR_ERROR_2 = Error.B70
    COLOR_ERROR_3 = Error.B110
    # Warning colors
    COLOR_WARN_1 = Warning.B40
    COLOR_WARN_2 = Warning.B70
    COLOR_WARN_3 = Warning.B50
    COLOR_WARN_4 = Warning.B40
    # Icon colors
    ICON_1 = Primary.B30
    ICON_2 = Secondary.B50
    ICON_3 = Success.B30
    ICON_4 = Error.B70
    ICON_5 = Warning.B70
    ICON_6 = Primary.B140
    ICON_7 = GroupLight.B90
    # Group colors
    GROUP_1 = GroupLight.B10
    GROUP_2 = GroupLight.B20
    GROUP_3 = GroupLight.B30
    GROUP_4 = GroupLight.B40
    GROUP_5 = GroupLight.B50
    GROUP_6 = GroupLight.B60
    GROUP_7 = GroupLight.B70
    GROUP_8 = GroupLight.B80
    GROUP_9 = GroupLight.B90
    GROUP_10 = GroupLight.B100
    GROUP_11 = GroupLight.B110
    GROUP_12 = GroupLight.B120
    # Highlight colors
    COLOR_HIGHLIGHT_1 = Secondary.B140
    COLOR_HIGHLIGHT_2 = Secondary.B130
    COLOR_HIGHLIGHT_3 = Secondary.B120
    COLOR_HIGHLIGHT_4 = Secondary.B110
    # Occurrence colors
    COLOR_OCCURRENCE_1 = Primary.B120
    COLOR_OCCURRENCE_2 = Primary.B110
    COLOR_OCCURRENCE_3 = Primary.B100
    COLOR_OCCURRENCE_4 = Primary.B90
    COLOR_OCCURRENCE_5 = Primary.B60
    # Logo colors
    PYTHON_LOGO_UP = Logos.B10
    PYTHON_LOGO_DOWN = Logos.B20
    SPYDER_LOGO_BACKGROUND = Logos.B30
    SPYDER_LOGO_WEB = Logos.B40
    SPYDER_LOGO_SNAKE = Logos.B50
    # Special tabs
    SPECIAL_TABS_SEPARATOR = Primary.B70
    SPECIAL_TABS_SELECTED = Secondary.B30
    # For the heart used to ask for donations
    COLOR_HEART = Error.B70
    # For editor tooltips
    TIP_TITLE_COLOR = Success.B20
    TIP_CHAR_HIGHLIGHT_COLOR = Warning.B30
    # Tooltip opacity (numeric value, not a color reference)
    OPACITY_TOOLTIP = 230

    # Border radius
    SIZE_BORDER_RADIUS = '4px'

    # Borders
    BORDER_1 = "1px solid $COLOR_BACKGROUND_1"
    BORDER_2 = "1px solid $COLOR_BACKGROUND_4"
    BORDER_3 = "1px solid $COLOR_BACKGROUND_6"

    BORDER_SELECTION_3 = "1px solid $COLOR_ACCENT_3"
    BORDER_SELECTION_2 = "1px solid $COLOR_ACCENT_2"
    BORDER_SELECTION_1 = "1px solid $COLOR_ACCENT_1"

    # Widget specific variables
    W_STATUS_BAR_BACKGROUND_COLOR = COLOR_ACCENT_1

    # Paths
    PATH_RESOURCES = "':/qss_icons'"


# =============================================================================
# ---- Exported classes
# =============================================================================
if is_dark_interface():
    SpyderPalette = SpyderPaletteDark
else:
    SpyderPalette = SpyderPaletteLight
