package:
  name: spyder
  version: {{ GIT_DESCRIBE_TAG|replace('v', '') }}

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  osx_is_app: True

source:
  git_url: ../

requirements:
  build:
    - python
    - sphinx
  run:
    - python
    - python.app  # [osx]
    - pyqt >=5.6.0
    - rope 0.9.*  # [py34 or py35]
    - rope  # [py27]
    - pyflakes
    - jedi
    - qtconsole >=4.2.0
    - nbconvert
    - pygments >=2.0
    - sphinx
    - pep8
    - psutil
    - pylint
    - qtawesome
    - qtpy >=1.1.0
    - pyzmq

about:
  home: https://github.com/spyder-ide/spyder
  license: MIT
  summary: Scientific PYthon Development EnviRonment
